# Generated by Django 6.0.7 on 2026-07-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='delivery_methods',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_methods',
        ),
    ]
