# Generated by Django 6.0.7 on 2026-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_delivery_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('like_new', 'like_new'), ('noted', 'noted'), ('damaged', 'damaged')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('reserved', 'reserved'), ('sold', 'sold'), ('removed', 'removed')], default='active', max_length=20),
        ),
    ]
