# Generated by Django 6.0.7 on 2026-07-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_condition_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photos',
            field=models.JSONField(default=list, help_text='完整照片網址陣列（R2 儲存後的公開 URL，見 ListingUploadURLView）'),
        ),
    ]
