# Generated by Django 6.0.7 on 2026-08-04 07:59

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_last_seen_bought_orders_at_and_more'),
        ('catalog', '0004_book_book_trgm_idx'),
        ('core', '0002_seed_categories'),
        ('listings', '0004_alter_listing_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['course_name'], name='listing_course_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
