# Generated by Django 6.0.7 on 2026-08-05 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='公司名稱', max_length=255)),
                ('contact_email', models.EmailField(help_text='聯絡信箱', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='聯絡電話', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='預留給未來廣告商登入用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='廣告標題，內部辨識用', max_length=255)),
                ('image_url', models.URLField(help_text='廣告橫幅圖片網址', max_length=500)),
                ('target_url', models.URLField(help_text='點擊後跳轉的網址', max_length=500)),
                ('position', models.CharField(default='home_banner', help_text='廣告位置', max_length=50)),
                ('start_date', models.DateTimeField(help_text='上架時間')),
                ('end_date', models.DateTimeField(help_text='下架時間')),
                ('is_active', models.BooleanField(default=True, help_text='是否啟用')),
                ('clicks_count', models.IntegerField(default=0, help_text='點擊次數統計')),
                ('views_count', models.IntegerField(default=0, help_text='曝光次數統計')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(help_text='所屬廣告商', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.advertiser')),
            ],
        ),
    ]
