# Generated by Django 6.0.7 on 2026-08-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_school_trgm_idx_user_user_trgm_idx'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='all_schools',
            field=models.BooleanField(default=True, help_text='是否適用於所有學校'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='schools',
            field=models.ManyToManyField(blank=True, help_text='適用的特定學校', related_name='advertisers', to='accounts.school'),
        ),
    ]
