# Generated by Django 6.0.7 on 2026-07-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_domain', models.CharField(help_text='例如: ntu.edu.tw', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Canonical English name, e.g. National Taiwan University', max_length=255)),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Localized fields per language, e.g. {"zh-TW": {"name": "國立台灣大學"}}')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='註冊信箱，可為任意信箱', max_length=254, unique=True)),
                ('edu_email', models.EmailField(blank=True, help_text='已驗證的校園信箱', max_length=254, null=True)),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('verified_at', models.DateTimeField(blank=True, help_text='首次通過 .edu.tw 驗證時間', null=True)),
                ('last_reverified_at', models.DateTimeField(blank=True, help_text='上一次重新驗證在校生身分的時間', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
