# Generated by Django 6.0.7 on 2026-07-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='頭貼網址', max_length=500, null=True),
        ),
    ]
