# Generated by Django 6.0.7 on 2026-07-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Canonical English name, e.g. College of Science', max_length=255)),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Localized fields per language, e.g. {"zh-TW": {"name": "理學院"}}')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='accounts.school')),
            ],
        ),
    ]
