# Generated by Django 6.0.7 on 2026-07-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='school',
        ),
    ]
