# Generated by Django 6.0.7 on 2026-07-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_college_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
