# Generated by Django 6.0.7 on 2026-07-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_bought_orders_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent bought order seen by the user', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_sold_orders_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent sold order seen by the user', null=True),
        ),
    ]
