# Generated by Django 6.0.7 on 2026-08-04 08:35

import django.contrib.postgres.indexes
from django.db import migrations


from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_last_seen_bought_orders_at_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='school',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'email_domain'], name='school_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email', 'first_name', 'last_name', 'edu_email'], name='user_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
