# Generated by Django 6.0.7 on 2026-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_latest_message_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='buyer_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
