# Generated by Django 6.0.7 on 2026-07-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='buyer_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
