# Generated by Django 6.0.7 on 2026-07-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversation_buyer_deleted_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
