# Generated by Django 6.0.7 on 2026-07-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('fake', 'fake'), ('scam', 'scam'), ('other', 'other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('actioned', 'actioned'), ('dismissed', 'dismissed')], default='open', max_length=20),
        ),
    ]
