# Generated by Django 6.0.7 on 2026-07-28 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_delete_message'),
        ('moderation', '0002_alter_report_reason_alter_report_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('harassment', 'harassment'), ('scam', 'scam'), ('spam', 'spam'), ('other', 'other')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('actioned', 'actioned'), ('dismissed', 'dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports', to='messaging.conversation')),
                ('reported_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
