# Generated by Django 6.0.7 on 2026-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_chatreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatreport',
            name='flagged_message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
