# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(blank=True, max_length=512)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('published_date', models.CharField(blank=True, max_length=50)),
                ('cover_url', models.URLField(blank=True, max_length=1024)),
                ('source', models.CharField(choices=[('listed', 'Listed'), ('preseed', 'Preseed'), ('manual', 'Manual'), ('google_api', 'Google Books API')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
