# Generated by Django 6.0.7 on 2026-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('listed', 'Listed'), ('preseed', 'Preseed'), ('manual', 'Manual'), ('google_api', 'Google Books API'), ('openlibrary_api', 'Open Library API')], max_length=20),
        ),
    ]
