# Generated by Django 6.0.7 on 2026-08-04 07:58

from django.db import migrations


from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_source'),
    ]

    operations = [
        TrigramExtension(),
    ]
