# Generated by Django 6.0.7 on 2026-07-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
