# Generated by Django 6.0.7 on 2026-07-22 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_delivery_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meetup_location',
            field=models.CharField(blank=True, help_text='Agreed meetup location', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='meetup_time',
            field=models.DateTimeField(blank=True, help_text='Agreed meetup time', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Requested)'), ('accepted', 'Accepted (Awaiting Meetup)'), ('handed_over', 'Handed Over (Awaiting Buyer Confirmation)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 rating. Null if no-show report.', null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_no_show', models.BooleanField(default=False, help_text='True if this is a report for a no-show.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('order', 'reviewer', 'reviewee')},
            },
        ),
    ]
